[package]
name = "image_sampler"
version = "0.1.0"
authors = ["end_sub"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
image = "0.23"
regex = "1"

